# Generated by Django 5.2.5 on 2025-11-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_menuitem_home_order_menuitem_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=250)),
                ('content_left_title', models.CharField(default='Our Story', max_length=150)),
                ('content_left_subtitle', models.CharField(blank=True, max_length=250)),
                ('content_left_body', models.TextField(blank=True)),
                ('content_right_title', models.CharField(default='Our Vision', max_length=150)),
                ('content_right_body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('open_hours_weekday', models.CharField(blank=True, default='8.00 AM - 8.00 PM', max_length=120)),
                ('open_hours_weekend', models.CharField(blank=True, default='2.00 PM - 8.00 PM', max_length=120)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('newsletter_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('quote', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
