# Generated by GitHub Copilot on 2025-12-11
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aboutsection_sitesetting_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('roast_type', models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('dark', 'Dark')], default='medium', max_length=20)),
                ('origin', models.CharField(help_text='Country or region of origin', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True)),
                ('flavor_notes', models.CharField(blank=True, help_text='e.g., Chocolate, Caramel, Fruity', max_length=255)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'ordering': ['name', 'id']},
        ),
    ]
